version: '3'

services:

  pmmidb:
    image: mysql:5.7
    networks:
      - back
    ports:
      - "3306"
    expose:
      - "3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./config/mysql/config:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswd
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal

  pmmiweb:
    image: pmguser/drupal-php7.0-apache:latest
    depends_on:
      - pmmidb
    links:
      - pmmidb
    networks:
      - front
      - back
    ports:
      - "8084:80"
    volumes:
      - .:/var/www
    # Environment variables
    environment:
      TERM: xterm
      # Drupal settings
      DRUPAL_PROFILE: minimal
      DRUPAL_SITE_NAME: Pack Expo International
      DRUPAL_USER: admin
      DRUPAL_PASS: admin
      DRUPAL_DBURL: mysql://root:rootpasswd@mysql:3306/drupal

networks:
  back:
    driver: bridge
  front:
    external: true
