version: '3'

services:

  pmmidb:
    container_name: "${SITE_CODE}_test_db"
    restart: always

  pmmiweb:
    container_name: "${SITE_CODE}_test_web"
    build:
      context: .
      dockerfile: Dockerfile-test
    restart: always
    environment:
      VIRTUAL_HOST: pmmistaging.pmmimediagroup.com,staging.pmmi.org

  pmmisolr:
    container_name: "${SITE_CODE}_test_solr"

  pmmivarnish:
    container_name: "${SITE_CODE}_test_varnish"
    image: pmguser/drupal-varnish:latest
    depends_on:
      - pmmiweb
    links:
      - pmmiweb
    networks:
      - back
    ports:
      - "8004:6081" # HTTP Proxy for testing purposes. On production we need to change this line to 80:6081
      - "8005:6082" # Control terminal
    volumes:
      - ./config/varnish/dev:/etc/varnish/
    environment:
      VARNISH_SECRET: secret
      VARNISH_BACKEND_HOST: 127.0.0.1
      VARNISH_BACKEND_PORT: 80
      VARNISH_MEMORY_SIZE: 256M
      VARNISH_STORAGE_SIZE: 1024M

  pmmimailhog:
    container_name: "${SITE_CODE}_test_mailhog"
    image: mailhog/mailhog
    networks:
      - back
    ports:
      - 1025:1025
      - "8006:8025"
