version: '2'
services:

  pmmidb:
    container_name: pmmi_test_db
    image: mysql:5.7
    networks:
      - back
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswd
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
    volumes:
      - ./data:/var/lib/mysql
      - ./config/mysql/config:/etc/mysql/conf.d
    ports:
      - "3307:3306"

  pmmiweb:
    container_name: pmmi_test_web
    image: pmguser/drupal-php7.0-apache:1.0.2
    depends_on:
      - pmmidb
      - pmmisolr
    networks:
      - front
      - back
    restart: always
    # Environment variables
    environment:
      TERM: xterm
      # Drupal settings
      DRUPAL_PROFILE: config_installer
      DRUPAL_SITE_NAME: PMMI
      DRUPAL_USER: admin
      DRUPAL_PASS: admin
      DRUPAL_DBURL: mysql://root:rootpasswd@mysql:3306/drupal
      VIRTUAL_HOST: staging.pmmi.org,pmmitest.pmmimediagroup.com
    volumes:
      - .:/var/www
      - ./config/cron:/etc/cron.d
    links:
      - pmmidb
      - pmmisolr

  pmmisolr:
    build: ./build/solr
    restart: always
    networks:
      - back
    ports:
      - "8003:8983"

  pmmivarnish:
    container_name: pmmi_test_varnish
    image: pmguser/drupal-varnish:1.0.0
    networks:
      - back
    volumes:
      - ./config/varnish/prod:/etc/varnish/
    restart: always
    environment:
      VARNISH_SECRET: secret
      VARNISH_BACKEND_HOST: pmmiweb
      VARNISH_BACKEND_PORT: 80
      VARNISH_MEMORY_SIZE: 256M
      VARNISH_STORAGE_SIZE: 1024M
    ports:
      - "80:6081"
      - "8005:6082" # Control terminal

networks:
  back:
    driver: bridge
  front:
    external: true
