# from https://www.drupal.org/requirements/php#drupalversions
FROM pmguser/drupal-php-7-apache:base-2.0.0
ARG DEBIAN_FRONTEND=noninteractive

# sSMTP: note php is configured to use ssmtp, which is configured to send to
# pximail:1025, which is standard configuration for a mailhog/mailhog image
# with hostname mail.
RUN apt-get update
RUN apt-get install ssmtp --fix-missing -y
COPY ./config/ssmtp/ssmtp.conf /etc/ssmtp/ssmtp.conf

RUN apt-get autoremove -y
