# from https://www.drupal.org/requirements/php#drupalversions
FROM pmguser/drupal-php7.0-apache:latest
ARG DEBIAN_FRONTEND=noninteractive

# Install Xdebug support
RUN pecl install xdebug \
  && docker-php-ext-enable xdebug \
  && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini
  # TODO: Figure out why this file can't be found during Docker build.
  # && cat cnf/php/xdebug.ini >> /usr/local/etc/php/conf.d/xdebug.ini

# Install PHPUnit
RUN curl -sSL https://phar.phpunit.de/phpunit.phar -o phpunit.phar && \
chmod +x phpunit.phar && \
mv phpunit.phar /usr/local/bin/phpunit
