version: '2'
services:
  db:
    container_name: pmmidb
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswd
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
    volumes_from:
      - mysqldata
    ports:
      - "3306:3306"
    expose:
      - "3306"

  web:
    container_name: pmmiweb
    depends_on:
      - db
    build:
      context: .
      dockerfile: drupal-php7.0-apache
    # Environment variables
    environment:
      # Drupal settings
      DRUPAL_PROFILE: minimal
      DRUPAL_SITE_NAME: pmmi
      DRUPAL_USER: admin
      DRUPAL_PASS: admin
      DRUPAL_DBURL: mysql://root:rootpasswd@mysql:3306/drupal
    ports:
      - "80:80"
      - "22:22"
    expose:
      - "80"
      - "22"
    volumes:
      - .:/var/www
    volumes_from:
      - drupaldata
    links:
      - db

  mysqldata:
    container_name: pmmimysqldata
    image: tianon/true
    volumes:
      - /var/lib/mysql

  drupaldata:
    container_name: pmmidrupaldata
    image: tianon/true
    volumes:
      - /var/www/html/sites/default/files
