version: '2'
services:

  pmmiweb:
    container_name: pmmi_dev_web_osx
    build:
      context: .
      dockerfile: Dockerfile-dev
    depends_on:
      - pmmidb
      - pmmisolr
    # Environment variables
    environment:
      TERM: xterm
      # Drupal settings
      DRUPAL_PROFILE: config_installer
      DRUPAL_SITE_NAME: PMMI
      DRUPAL_USER: admin
      DRUPAL_PASS: admin
      DRUPAL_DBURL: mysql://root:rootpasswd@mysql:3306/drupal
      PHP_XDEBUG_ENABLED: 1
      PHP_XDEBUG_AUTOSTART: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 1         # This is needed to respect remote.host setting bellow
      PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"
    volumes:
      - pmmi-unison-sync:/var/www:rw # Replace volume to this to use docker-sync for macOS users
    links:
      - pmmidb
      - pmmisolr
    ports:
      - "8080:80"
    expose:
      - "80"
      - "9000"

  pmmidb:
    extends:
      file: docker-compose.yml
      service: pmmidb

  pmmisolr:
    extends:
      file: docker-compose.yml
      service: pmmisolr

  pmmivarnish:
    container_name: pmmi_dev_varnish
    image: pmguser/drupal-varnish:latest
    depends_on:
      - pmmiweb
    volumes:
      - ./config/varnish:/etc/varnish/
    environment:
      VARNISH_SECRET: secret
      VARNISH_BACKEND_HOST: pmmiweb
      VARNISH_BACKEND_PORT: 80
      VARNISH_MEMORY_SIZE: 256M
      VARNISH_STORAGE_SIZE: 1024M
    ports:
      - "8004:6081" # HTTP Proxy for testing purposes. On production we need to change this line to 80:6081
      - "8005:6082" # Control terminal

volumes:
  pmmi-unison-sync:
    external: true
