map:
  audience_1:
    audience_title: 'Audience 1'
    audience_redirect_url: 'internal:/home'
    audience_image: {  }
  audience_2:
    audience_title: 'Audience 2'
    audience_redirect_url: 'internal:/home'
    audience_image: {  }
  audience_3:
    audience_title: 'Audience 3'
    audience_id: audience_3
    audience_redirect_url: 'internal:/home'
    audience_image: {  }
gateway_url: 'internal:/gateway'
