pmmi_sales_agent.mail_settings:
  type: config_object
  label: 'PMMI Sales Agent Mail Settings'
  mapping:
    mail_notification_address:
      type: email
      label: 'Notification email address'
    remind_period:
      type: integer
      label: 'Remind period'
    submission_alert:
      type: text
      label: 'Submission alert message'
    ss_update:
      type: mail
      label: 'Self-service update your listing'
    ss_update_reminder:
      type: mail
      label: 'Self-service update your listing (reminder)'
    listing_approve:
      type: mail
      label: 'Listing has been approval'
    listing_reject:
      type: mail
      label: 'Listing has been rejected'
    listing_create:
      type: mail
      label: 'New listing has been created'
    listing_review:
      type: mail
      label: 'Listing is pending review'

pmmi_sales_agent.mail_mass_settings:
  type: config_object
  label: 'PMMI Sales Agent Mass Mail Settings'
  mapping:
    filter:
      type: string
      label: 'Send an email to'
    remind_period:
      type: integer
      label: 'Remind period'
    last_run:
      type: integer
      label: 'Last run'
