pmmi_sales_agent.mail_settings:
  type: config_object
  label: 'PMMI Sales Agent Mail Settings'
  mapping:
    mail_notification_address:
      type: email
      label: 'Notification email address'
    ss_update:
      type: mail
      label: 'Self-service update your listing'
    ss_update_reminder:
      type: mail
      label: 'Self-service update your listing (reminder)'

pmmi_sales_agent.mail_mass_settings:
  type: config_object
  label: 'PMMI Sales Agent Mass Mail Settings'
  mapping:
    filter:
      type: string
      label: 'Send an email to'
    remind_period:
      type: integer
      label: 'Remind period'
    last_run:
      type: integer
      label: 'Last run'
