<?php

/**
 * @file
 *
 * Main file of module.
 */

/**
 * @todo
 * Implement hooks below.
 */

/**
 * Implements hook_entity_insert().
 */
function pmmi_page_manager_search_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'page_variant') {
    $page_manager_search = \Drupal::entityTypeManager()->getStorage('page_manager_search')->loadMultiple([]);
  }
}

/**
 * Implements hook_entity_update().
 */
function pmmi_page_manager_search_entity_update(Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'page_variant') {
    $exist_page_manager_search = \Drupal::entityQuery('page_manager_search')
      ->condition('pid', $entity->id())
      ->execute();

    if (empty($exist_page_manager_search)) {
      $page = $entity->getPage();

      $render = \Drupal::entityTypeManager()
        ->getViewBuilder('page_variant')
        ->view($entity);

      $content = \Drupal::service('renderer')->renderRoot($render);
      $content = strip_tags($content);
      $content = trim(preg_replace('/\s+/', ' ', $content));

      $page_manager_search = \Drupal::entityTypeManager()
        ->getStorage('page_manager_search')
        ->create([
          'pid' => $entity->id(),
          'title' => $entity->label(),
          'content' => $content,
          'path' => $page->getPath(),
          ]);

    }
    $b=0;
  }
}

/**
 * Implements hook_entity_delete().
 */
function pmmi_page_manager_search_entity_delete(Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'page_variant') {
    $page_manager_search = \Drupal::entityTypeManager()->getStorage('page_manager_search')->loadMultiple([]);
  }
}
