<?php

/**
 * @file
 * Extends functionality of address module.
 */

/**
 * Implements hook_field_widget_form_alter().
 */
function pmmi_address_field_widget_form_alter(&$element, \Drupal\Core\Form\FormStateInterface $form_state, $context) {
  $field_definition = $context['items']->getFieldDefinition();
  if ($field_definition->getType() == 'country_area') {
    $element['country_code']['#title'] = t('You can select as many countries as you want:');
    $element['administrative_area']['#title'] = t('You can select as many states/regions as you want:');
  }
}
