<?php

/**
 * @file
 * Update hooks for the 'PMMI Sales Agent Directory' module.
 */

use Drupal\Core\Database\Database;

/**
 * Implements hook_schema().
 */
function pmmi_sales_agent_schema() {
  $schema['pmmi_sales_agent_mails'] = array(
    'description' => 'Stores information about sales agent mails.',
    'fields' => array(
      'mid'  => array(
        'type' => 'serial',
        'not null' => TRUE,
        'description' => 'The mail ID.',
      ),
      'nid' => array(
        'description' => 'The node ID.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'type' => array(
        'type' => 'varchar',
        'length' => 128,
        'not null' => TRUE,
        'default' => '',
        'description' => 'The mails type.',
      ),
      'sending_date' => array(
        'description' => 'The Unix timestamp when mail should be sent.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
    ),
    'primary key' => array('mid'),
    'indexes' => array(
      'type' => array('type'),
      'sending_date' => array('sending_date'),
    ),
    'foreign keys' => array(
      'nid' => array('node' => 'nid'),
    ),
  );

  $schema['pmmi_sales_agent_search_stats'] = [
    'description' => 'Stores information about usage of the search agent directory.',
    'fields' => [
      'id' => [
        'type' => 'serial',
        'not null' => TRUE,
        'description' => 'The ID of a statistic point.',
      ],
      'uid' => [
        'description' => 'The user ID of the user on which the statistic point was written.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ],
      'date' => [
        'description' => 'The Unix timestamp when record has been added.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ],
      'countries_searched' => [
        'type' => 'varchar',
        'length' => 128,
        'not null' => TRUE,
        'default' => '',
        'description' => 'The countries which were searched.',
      ],
    ],
    'primary key' => ['id'],
    'indexes' => [
      'date' => ['date'],
      'countries_searched' => ['countries_searched'],
    ],
    'foreign keys' => [
      'uid' => ['users' => 'uid'],
    ],
  ];

  return $schema;
}

/**
 * Revert configuration to the value from extension storage.
 */
function pmmi_sales_agent_update_8005() {
  \Drupal::service('module_installer')->install(['config_update'], TRUE);
  \Drupal::service('config_update.config_update')->revert('system.simple', 'pmmi_sales_agent.mail_settings');
  \Drupal::service('config_update.config_update')->revert('system.simple', 'pmmi_sales_agent.mail_mass_settings');
}

/**
 * Revert configuration to set default value for mail settings.
 */
function pmmi_sales_agent_update_8006() {
  \Drupal::service('config_update.config_update')->revert('system.simple', 'pmmi_sales_agent.mail_settings');
}

/**
 * Creates the 'pmmi_sales_agent_mails' table.
 */
function pmmi_sales_agent_update_8007() {
  $schema = Database::getConnection()->schema();

  if (!$schema->tableExists('pmmi_sales_agent_mails')) {
    $spec = drupal_get_module_schema('pmmi_sales_agent', 'pmmi_sales_agent_mails');
    $schema->createTable('pmmi_sales_agent_mails', $spec);
  }
}

/**
 * Set default value for the 'pmmi_sales_agent.mail_settings' config.
 */
function pmmi_sales_agent_update_8008() {
  \Drupal::service('config.factory')->getEditable('pmmi_sales_agent.mail_settings')
    ->set('remind_period', 604800)
    ->save();
}

/**
 * Creates the 'pmmi_sales_agent_search_stats' table.
 */
function pmmi_sales_agent_update_8009() {
  $schema = Database::getConnection()->schema();

  if (!$schema->tableExists('pmmi_sales_agent_search_stats')) {
    $spec = drupal_get_module_schema('pmmi_sales_agent', 'pmmi_sales_agent_search_stats');
    $schema->createTable('pmmi_sales_agent_search_stats', $spec);
  }
}
