<?php

/**
 * @file
 * Contains pmmi_forms.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Url;

/**
 * Implements hook_form_alter().
 */
function pmmi_forms_form_alter(array &$form, FormStateInterface $form_state) {
  switch ($form['#form_id']) {
    case 'block_content_image_slide_form':
    case 'block_content_image_slide_edit_form':
      $form['field_image']['#states'] = array(
        'invisible' => array(
          ':input[name="field_slide_type"]' => array('value' => 'video'),
        ),
      );
      $form['field_video']['#states'] = array(
        'invisible' => array(
          ':input[name="field_slide_type"]' => array('value' => 'image'),
        ),
      );
      array_unshift($form['#validate'], 'pmmi_forms_image_slide_validate');
      break;

    case 'block_content_containers_form':
    case 'block_content_containers_edit_form':
      $fields = ['field_block_', 'field_block_plugin_', 'field_block_views_'];
      for ($i = 1; $i < 7; $i++) {
        foreach ($fields as $field) {
          $form[$field . $i]['#states'] = array(
            'visible' => array(
              'select[name="field_block_select_' . $i . '"]' => [
                'value' => $field . $i,
              ],
            ),
          );
        }
      }
      array_unshift($form['actions']['submit']['#submit'], 'block_content_containers_form_submit');
      array_unshift($form['#submit'], 'block_content_containers_form_submit');
      break;

    case 'node_company_form':
    case 'node_company_edit_form':
      // Hide unnecessary data from the display.
      $form['advanced']['#access'] = FALSE;
      $form['revision_information']['#access'] = FALSE;
      $form['menu']['#access'] = FALSE;

      // Only 'Register' submit is needed for the "Company" content type.
      $form['actions']['submit']['#access'] = TRUE;
      $form['actions']['submit']['#value'] = t('Register');
      foreach (array('publish', 'unpublish', 'preview', 'delete') as $button) {
        if (isset($form['actions'][$button])) {
          $form['actions'][$button]['#access'] = FALSE;
        }
      }
      break;

    case 'views_exposed_form':
      if ($form['#id'] === 'views-exposed-form-news-search-api-paged') {
        $current_year = intval(date("Y"));
        $break_year = intval(date("Y")) - 5;

        $options = [];
        $options['All'] = '- Any -';
        while ($current_year > $break_year) {
          if ($current_year === intval(date("Y"))) {
            $options[intval(date("Y"))] = 'Current';
          }
          else {
            $options[$current_year] = $current_year;
          }
          $current_year--;
        }
        // Add custom form element for emulating `Filter by Year` filter and hide
        // Date field (operator: is between).
        $form['filter_by_year']['#title'] = t('Filter by Year');
        $form['filter_by_year']['#type'] = 'select';
        $form['filter_by_year']['#options'] = $options;
        $form['filter_by_year']['#default_value'] = intval(date("Y"));
        $form['filter_by_year']['#attributes']['size'] = 1;
        $form['year']['#type'] = 'hidden';
        array_unshift($form['#submit'], 'pmmi_forms_custom_filter_by_year_submit');
      }

      break;
  }
}

/**
 * Custom callback function for filtering news by year.
 *
 * @todo
 * Needs to be changed when Date Views filter will be available for Drupal 8.
 *
 */
function pmmi_forms_custom_filter_by_year_submit(array &$form, FormStateInterface &$form_state) {
  $values = $form_state->getValues();
  // Manually set values in min and max fields for `Date filter` based on
  // select value in custom form element.
  if ($values['filter_by_year'] !== 'All' && is_numeric($values['filter_by_year'])) {
    $form_state->setValue([
      'year',
      'min',
    ], $values['filter_by_year'] . '-01-01');
    $form_state->setValue([
      'year',
      'max',
    ], $values['filter_by_year'] . '-12-31');
  }
  else {
    $form_state->setValue(['year', 'min'], NULL);
    $form_state->setValue(['year', 'max'], NULL);
    $form_state->setValue('filter_by_year', NULL);
  }
}

/**
 * Validation for image slide form.
 *
 * Do validation of video or image field based on selected slide type.
 */
function pmmi_forms_image_slide_validate(array &$form, FormStateInterface &$form_state) {
  $slide_type = $form_state->getValue('field_slide_type')[0]['value'];
  $element_name = ($slide_type == 'image') ? 'field_image' : 'field_video';
  $slide_value = $form_state->getValue($element_name);
  $element = $form[$element_name]['widget'];
  if (($slide_type == 'image' && empty($slide_value['target_id']))
  || ($slide_type == 'video' && empty($slide_value[0]['value']))) {
    $form_state->setError($element, t('@name field is required.', array('@name' => $element['#title'])));
  }
}

/**
 * Containers block submit function.
 */
function block_content_containers_form_submit($form, FormStateInterface $form_state) {
  $values = $form_state->getValues();
  // Get all select fields.
  $selects = array_filter($values, function($key) {
    return strpos($key, 'field_block_select_') === 0;
  }, ARRAY_FILTER_USE_KEY);

  // Filter all fields values based on selected field in group.
  foreach ($selects as $key => $select_field) {
    // Current select field delta.
    $delta = str_replace('field_block_select_', '', $key);
    // Fields list.
    $fields = [
      'field_block_' . $delta,
      'field_block_plugin_' . $delta,
      'field_block_views_' . $delta,
    ];
    // Remove selected field from list.
    $selected_field = !empty($select_field) ? $select_field[0]['value'] : '';
    $fields = array_diff($fields, [$selected_field]);

    // Clean values from unselected fields.
    foreach ($fields as $field) {
      $form_state->setValue($field, []);
      if ($field === 'field_block_' . $delta && isset($values['field_block_' . $delta]['entities'])) {
        $inline_entity_form = &$form_state->get('inline_entity_form');
        $keys = array_keys($inline_entity_form);
        $inline_entity_form[$keys[(int) $delta - 1]]['entities'] = [];
      }
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_create_access().
 *
 * Add access for creating webform options entity if user has
 * create webform permission.
 */
function pmmi_forms_webform_options_create_access(\Drupal\Core\Session\AccountInterface $account, array $context, $entity_bundle) {
  return AccessResult::allowedIf($account->hasPermission('create webform'))->cachePerPermissions()->cachePerUser();
}

/**
 * Implements hook_ENTITY_TYPE_access().
 *
 * Add access for edit/delete webform options entity if user has
 * create webform permission.
 */
function pmmi_forms_webform_options_access(EntityInterface $entity, $operation, AccountInterface $account) {
  if (in_array($operation, ['update', 'delete'])) {
    return AccessResult::allowedIf($account->hasPermission('create webform'))->cachePerPermissions()->cachePerUser();
  }
}

/**
 * Implements hook_ENTITY_TYPE_access().
 *
 * Add access for viewing webform submission.
 */
function pmmi_forms_webform_submission_access(EntityInterface $entity, $operation, AccountInterface $account) {
  if ($entity && $webform = $entity->getWebform()) {
    if ($operation == 'view' && $webform->id() == 'membership_application_form'
    && in_array('membership_committee', $account->getRoles())) {
      return AccessResult::allowed()->cachePerPermissions()->cachePerUser();
    }
  }
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function pmmi_forms_menu_local_tasks_alter(&$data, $route_name) {
  $user = \Drupal::currentUser();
  $roles = $user->getRoles();
  $routes = [
    'entity.webform.collection',
    'entity.webform_options.collection',
    'entity.webform_submission.collection',
  ];

  if (!in_array('administrator', $roles) && $user->hasPermission('create webform')
  && in_array($route_name, $routes)) {
    $data['tabs'][0]['webform.options'] = array(
      '#theme' => 'menu_local_task',
      '#link' => array(
        'title' => t('Manage options'),
        'url' => Url::fromRoute('entity.webform_options.collection'),
        'localized_options' => array(
          'attributes' => array(
            'title' => t('Manage options'),
          ),
        ),
      ),
      '#active' => $route_name == 'entity.webform_options.collection',
    );
  }
}
