<?php

/**
 * @file
 * Contains pmmi_personify.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pmmi_personify_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pmmi_personify module.
    case 'help.page.pmmi_personify':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('PMMI Personify Integration') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function pmmi_personify_theme() {
  return [
    'pmmi_personify' => [
      'template' => 'pmmi_personify',
      'render element' => 'children',
    ],
  ];
}
