# Schema for the configuration files of the XHProf module.
xhprof.config:
  type: mapping
  label: 'XHProf configuration'
  mapping:
    enabled:
      type: boolean
      label: 'XHProf enabled'
    extension:
      type: string
      label: 'Choose the extension to use for profiling'
    exclude:
      type: string
      label: 'Path to exclude'
    interval:
      type: integer
      label: 'The approximate number of requests between XHProf samples. Leave empty to profile all requests'
    flags:
      type: sequence
      label: 'Flags to choose what profile'
      sequence:
        - type: string
          label: 'Toolbar item'
    exclude_indirect_functions:
      type: boolean
      label: 'Exclude indirect functions'
    storage:
      type: string
      label: 'Choose the XHProf storage class'
    show_summary_toolbar:
      type: boolean
      label: 'Show summary data in toolbar'
