module:
  breakpoint: 0
  ckeditor: 0
  config: 0
  config_update: 0
  contextual: 0
  dynamic_page_cache: 0
  editor: 0
  features: 0
  features_ui: 0
  field: 0
  file: 0
  filter: 0
  link: 0
  menu_link_content: 0
  menu_ui: 0
  node: 0
  page_cache: 0
  pmmi: 0
  quickedit: 0
  system: 0
  taxonomy: 0
  text: 0
  toolbar: 0
  update: 0
  user: 0
  views: 0
theme:
  stark: 0
  stable: 0
  classy: 0
  seven: 0
  bootstrap: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
