module:
  audience_select: 0
  block: 0
  breakpoint: 0
  ckeditor: 0
  config: 0
  config_split: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dynamic_page_cache: 0
  editor: 0
  entity_browser: 0
  field: 0
  file: 0
  filter: 0
  image: 0
  inline_entity_form: 0
  link: 0
  link_attributes: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  node: 0
  page_cache: 0
  pmmi: 0
  quickedit: 0
  serialization: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  views: 0
theme:
  stable: 0
  classy: 0
  seven: 0
  bootstrap: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
