categories:
  - BENCHMARKING
  - ECONOMIC-TRENDS
  - INDUSTRY-RPTS
  - INTL-RESEARCH
_core:
  default_config_hash: poyaxSljCjrwZ5nbuDqNVYroKBPwypg5ls5k2u2rq98
images_base_path: 'https://pmmiprod3ebiz.personifycloud.com/ProductImages/'
