login_uri: 'https://pmmiprod3ebiz.personifycloud.com/SSO/login.aspx'
service_uri: 'https://pmmiprod3ebiz.personifycloud.com/sso/webservice/service.asmx'
vi: '14'
vu: PMG
vp: B5996798E5428FDC01DAD7BFC972D73E
vib: CE32886246107DA7747ED3D55553CD6C
expiration: '3600'
gateway:
  check_frequency: -2
  paths:
    id: request_path
    pages: "/about\r\n/about/*"
    negate: false
advanced:
  debug_log: true
  connection_timeout: 10
data_service:
  endpoint: 'https://pmmiprod3ebiz.personifycloud.com/PersonifyDataServices/personifydatapmmi.svc'
  username: SUMMIT
  password: pmg@123
