apikey: 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
test_defaults:
  to: example@mail.com
  subject: ''
  body:
    value: ''
    format: plain_text
  from_name: Test User
  to_name: ''
  reply_to: ''
_core:
  default_config_hash: g4qz7cPnloXFwtnLYfIKI2VS0gf_UFOz_I2uQiiulC8
