import: 0
expire: '0'
consumer_key: wqWtBGivZNz2L0pnX6b9SlGl1
consumer_secret: byYJ5cDsAX27nLQdZvBvLyReq8svyGRABWZEqBGAd1vKvD8oNK
host: 'https://twitter.com'
api: 'https://api.twitter.com'
search: 'https://twitter.com/search'
tinyurl: 'http://tinyurl.com'
