# Schema for the configuration files of the Audience Select module.

audience_select.settings:
  type: config_object
  label: 'Audience Select settings'
  mapping:
    audiences:
      type: string
      label: 'Audiences:'
      translatable: true
