# Schema for the configuration files of the Audience Select module.

audience_select.settings:
  type: config_object
  label: 'Audience Select settings'
  mapping:
    audiences:
      type: string
      label: 'Audiences:'
      translatable: true
    gateway_page_url:
      type: string
      label: 'Gateway page URL'
      translatable: false

condition.plugin.audience:
  type: condition.plugin
  mapping:
    audience:
      type: sequence
      sequence:
        type: string
