<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function audience_select_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.audience_select':
      return t('
        <h2>Audience Select for Drupal.</h2>
        <h3>Instructions</h3>
        <p>Unpack in the <em>modules</em> folder (currently in the root of your Drupal 8 installation) and enable in <strong>/admin/modules</strong>.</p>
        <p>Then, visit <strong>/admin/config/custom/audience_select</strong> and enter your own set of audiences.</p>
        <p>If you need, there\'s also a specific <em>set audiences</em > permission .</p >
      ');
  }
}


/**
 * Implements hook_theme().
 */
function audience_select_theme($existing, $type, $theme, $path) {
  $audiences = \Drupal\audience_select\Controller\AudienceSelectController::getAllAudiences();
  //var_dump($audiences);
  return [
    'page__gateway' => [
      'variables' => ['audiences' => $audiences],
      'template' => 'page--gateway',
    ],
    'audience_switcher_block' => [
      'variables' => ['audiences' => $audiences],
      'template' => 'audience-switcher-block',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function audience_select_preprocess_page__gateway(&$variables) {
  $variables['audiences'] = \Drupal\audience_select\Controller\AudienceSelectController::getAllAudiences();
}
