<?php

/**
 * @file
 * Contains pmmi_training_provider.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function pmmi_training_provider_form_alter(array &$form, FormStateInterface $form_state) {
  switch ($form['#form_id']) {
    case 'node_training_provider_form':
    case 'node_training_provider_edit_form':
      // Hide unnecessary data from the display.
      $form['advanced']['#access'] = FALSE;
      $form['revision_information']['#access'] = FALSE;
      $form['menu']['#access'] = FALSE;
  }
}
